name: Automatic Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production-auto

    steps:
      - uses: actions/checkout@v4

      - name: Automatic Deployment
        run: echo "Automatically deploying to production-auto"

