name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: echo "Deploying application to Staging environment"

  deploy-to-production:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "Deploying application to Production environment"
